[workspace]
members = ["elite_gold", "tourney", "loot_survivor"]

[workspace.package]
version = "0.0.0"
description = "Loot Survivor Mods"
authors = ["loaf"]

[workspace.dependencies]
starknet = "=2.4.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }
loot_survivor = { path = "loot_survivor" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.13.1" }
